let musicDB = [
  {
    id: 0,
    name: "Shakedown",
    author_name: "Clarx",
    img: "shakedown.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Clarx - Shakedown [NCS Release].mp3",
    attribution: {
      song: "Clarx - Shakedown [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },
  {
    id: 1,
    name: "Games Worldbeat",
    author_name: "Bernardo R.",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "mixkit-games-worldbeat-466.mp3",
    attribution: {
      song: "Games Worldbeat",
      musicBy: "mixkit",
      download: null,
      stream: null,
    },
  },
  {
    id: 2,
    name: "Yagon yagon",
    author_name: "Farzonai Khurshed",
    img: "1613725174_farzonai_hurshed.jpg",
    lang: "Tajik",
    type: "electronic",
    timesPlayed: 0,
    musicName: "farzonai-hurshed-yagon-yagon.mp3",
    attribution: {
      song: "ROY KNOX - Over My Head (Feat. Mike Robert) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },

  {
    id: 3,
    name: "Plohaya",
    author_name: "Islam Itlyashev",
    img: "33774870.jpg",
    lang: "Russian",
    timesPlayed: 0,
    type: "electronic",
    musicName: "islam_itlyashev_-_plohaya.mp3",
    attribution: {
      song: "Islam Itlyashev - Plohaya [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/WantYou",
      stream: "http://youtu.be/Pww31vN_1QY",
    },
  },
  {
    id: 4,
    name: "Apocalypse",
    author_name: "Midranger",
    img: "apocalypse-1600776027-tsCmgK4gEU.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Midranger - Apocalypse [NCS Release].mp3",
    attribution: {
      song: "Midranger - Apocalypse [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/Apocalypse",
      stream: "http://youtu.be/Whw1sWDpAvE",
    },
  },
  {
    id: 5,
    name: "Tra",
    author_name: "Baron",
    img: "notAvailable.jpg",
    lang: "Tajik",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Baron - Тра.mp3",
    attribution: {
      song: "Baron - Тра",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/NAlive",
      stream: "http://youtu.be/vJAcXd_UtWQ",
    },
  },
  {
    id: 6,
    name: "Yamakasi",
    author_name: "Miyagi, Andy Panda",
    img: "yamakasi.jpg",
    lang: "Russian",
    timesPlayed: 0,
    type: "electronic",
    musicName: "1594976746_miyagi-andy-panda-yamakasi.mp3",
    attribution: {
      song: "Miyagi, Andy Panda - Yamakasi [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/Ignite",
      stream: "http://youtu.be/zbqgv0mMfwk",
    },
  },
  {
    id: 7,
    name: "Impact Moderato 2",
    author_name: "Kevin MacLeod",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "impact2.mp3",
    attribution: {
      song: "Impact Moderato",
      musicBy: "Kevin MacLeod",
      download: null,
      stream: null,
    },
  },
  {
    id: 8,
    name: "Ассалом эй гули лола",
    author_name: "Ad Aka Dilovar, ROYCE",
    img: "notAvailable.jpg",
    lang: "Tajik",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Ad Aka Dilovar, ROYCE - Ассалом эй гули лола.mp3",
    attribution: {
      song: "Ad Aka Dilovar, ROYCE - Ассалом эй гули лола [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },
  {
    id: 9,
    name: "Captain",
    author_name: "Miyagi",
    img: "captain.jpg",
    lang: "Russian",
    timesPlayed: 0,
    type: "electronic",
    musicName: "miyagi-captain.mp3",
    attribution: {
      song: "miyagi-captain [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },
  {
    id: 10,
    name: "Impact Moderato",
    author_name: "Kevin MacLeod",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "impact.mp3",
    attribution: {
      song: "Impact Moderato",
      musicBy: "Kevin MacLeod",
      download: null,
      stream: null,
    },
  },
  {
    id: 11,
    name: "Want You (feat. Sara Skinner)",
    author_name: "Subtact, Sara Skinner",
    img: "want-you-feat-sara-skinner-1586956276-s4lOrfrHQj.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Subtact - Want You (feat. Sara Skinner) [NCS Release].mp3",
    attribution: {
      song: "Subtact - Want You (feat. Sara Skinner) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },
  {
    id: 12,
    name: "Alive",
    author_name: "Neoni, N3WPORT",
    img: "alive.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "N3WPORT - Alive (feat. Neoni) [NCS Release].mp3",
    attribution: {
      song: "N3WPORT - Alive (feat. Neoni) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },
  {
    id: 13,
    name: "Ignite",
    author_name: "Tom wilson, Heuse",
    img: "ignite-1600419626-nHn4WXY79q.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Heuse & Tom Wilson - Ignite [NCS Release].mp3",
    attribution: {
      song: "Heuse & Tom Wilson - Ignite [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },
  {
    id: 14,
    name: "OverMyHead",
    author_name: " ROY KNOX",
    img: "over-my-head-1602154826-mOiKzOJDe6.jpg",
    lang: "ENGLISH",
    type: "electronic",
    timesPlayed: 0,
    musicName: "ROY KNOX -  Over My Head (Feat. Mike Robert) [NCS Release].mp3",
    attribution: {
      song: "ROY KNOX - Over My Head (Feat. Mike Robert) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: null,
    },
  },
];

export default musicDB;
